# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Gamio' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Gamio

pod 'Alamofire'
pod 'AlamofireImage', '~> 4.1'
pod 'L10n-swift', '~> 5.10'
pod 'SwiftEntryKit', '2.0.0'
pod 'NVActivityIndicatorView'
  target 'GamioTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'GamioUITests' do
    # Pods for testing
  end

end
